[workspace]
resolver = "2"

members = ["crates/circuit","crates/kzg",
    "crates/setup",
]

[workspace.dependencies]
ark-ff = "0.5"
ark-ec = "0.5"
ark-poly = "0.5"
ark-bls12-381 = "0.5"
ark-std = "0.5"
rand = "0.8"
sha2 = "0.10"
