[package]
name = "setup"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true
ark-poly.workspace = true
ark-std.workspace = true
rand.workspace = true
sha2.workspace = true
