[package]
name = "proof"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-ff = { workspace = true }
ark-bls12-381 = { workspace = true }
ark-poly = { workspace = true }
circuit = { path = "../circuit" }
kzg = { path = "../kzg" }
setup = { path = "../setup" }
